
# Hello!

# run this script first!

# to run code, select the code and press control + enter!

# Once you've downloaded R Studio, you need to install the set of packages used in the scripts:

install.packages("stringi")
install.packages("stringr")
install.packages("reshape2")
install.packages("pvclust")
install.packages("devtools")
install.packages("backports")
install.packages("Hmisc")
install.packages("tibble")
install.packages("ggpubr")
install.packages("cluster")
install.packages("factoextra")
install.packages("gridExtra")
install.packages("lmerTest")
install.packages("papaja")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tibble")
install.packages("afex")
install.packages("citr")
install.packages("igraph")
install.packages("fields")
install.packages("poweRlaw")
install.packages("feather")
install.packages("effects")
install.packages("MuMIn")
install.packages("brms")
install.packages("glmmTMB")
install.packages("dfoptim")
install.packages("DHARMa")

# you only need to run these once, so comment them out after installing, using control + shift + c

# now install the packages into your R library

library(tidyverse)
library(stringi)
library(stringr)
library(reshape2)
library(pvclust)
library(ggplot2)
library(tibble)
library(ggpubr)
library(cluster)
library(factoextra)
library(gridExtra)
library(lmerTest)
library(papaja)
library(tidyverse)
library(dplyr)
library(afex)
library(citr)
library(igraph)
library(fields)
library(poweRlaw)
library(feather)
library(ggthemes)
library(effects)
library(nlme)
library(MuMIn)
library(brms)
library(lattice)
library(effects)
library(sjPlot)
library(glmmTMB)
library(afex)
library(dfoptim)
library(DHARMa)
citation("DHARMa")
library(ggeffects)
library(broom)

